services:

  # Prometheus时序数据库
  # 监听9090端口
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: on-failure:3
    networks:
      common:
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.enable-admin-api"
    volumes:
      - prometheus:/etc/prometheus
      - prometheusData:/prometheus
    # ports:
    #   - 9090:9090
    # healthcheck:
    # environment:
    labels:
      com.centurylinklabs.watchtower.enable: "true"

volumes:
  prometheusData:
  prometheus:

networks:
  # 使用公共的Network
  common:
    external: true